const dishes = [
  {
    id: 1,
    rank: '#1 Most loved dish',
    titleLight: 'LOTEK',
    titleBold: 'PERKEDEL',
    plate: 'round',
    accent: '#ef9548',
    palette: ['#8a9b5e', '#e4d9b4', '#c96f3a', '#f3ece0'],
    rating: '4.9',
    chef: 'Chef Feny',
    place: 'Dapur Umum Tamanan',
    quote:
      '"Kau terindah kan selalu terindah, apalagi masakanmu. Ahayy malah nge-gombal si abang."',
    likes: 96,
    ingredients: ['Steamed vegetables', 'Peanut sauce', 'Grated coconut', 'Fried perkedel'],
    thumbLabel: 'Soto Sapi',
  },
  {
    id: 2,
    rank: '#2 Most loved dish',
    titleLight: 'LAMB STEAK',
    titleBold: 'POTATO',
    plate: 'round',
    accent: '#ec9fc0',
    palette: ['#7a4632', '#c0392b', '#e3a857', '#f4ece2'],
    rating: '4.3',
    chef: 'Chef K. Semy',
    place: 'Komunitas Pecinta Steak',
    quote:
      '"Dosen pembimbingku kok asem tenan yo rek, masak ket wingi ra teko-teko. Suff suff."',
    likes: 58,
    ingredients: ['Grilled lamb loin', 'Roasted cherry tomato', 'Shoestring fries', 'Herb butter'],
    thumbLabel: 'Lamb Steak',
  },
  {
    id: 3,
    rank: '#3 Most loved dish',
    titleLight: 'MARTABAK',
    titleBold: 'PAK ADIN',
    plate: 'square',
    accent: '#a9cf85',
    palette: ['#2f5233', '#6b8f3f', '#e8b923', '#f2ede1'],
    rating: '4.6',
    chef: 'Chef Adin Salma',
    place: 'Warteg Mas Pur',
    quote:
      '"Dengan modus \'neng mabar yuk\' akhirnya Adin sukses menjadi juragan penerus Mas Pur."',
    likes: 36,
    ingredients: ['Shredded kale', 'Pan-seared tofu', 'Blueberry', 'Pumpkin seed'],
    thumbLabel: 'Martabak',
  },
  {
    id: 4,
    rank: '#4 Most loved dish',
    titleLight: 'URAP ASLI',
    titleBold: 'WONOGIRI',
    plate: 'round',
    accent: '#f2c94c',
    palette: ['#d9a441', '#8b5e2b', '#4c3a2b', '#f4e9d8'],
    rating: '4.5',
    chef: 'Chef Reza',
    place: 'Sushi Tei',
    quote:
      '"Designer nyambi chef, setelah menikahi gadis south mountain yang lama dinanti."',
    likes: 74,
    ingredients: ['Grated coconut sambal', 'Blanched greens', 'Roasted peanut', 'Fried shallot'],
    thumbLabel: 'Urap Asli',
  },
];

export default dishes;
